### ISSUE TITLE
Wix Implementation

### ISSUE THREAD

**Issue by WPBIII** [Salman2301/wix-chartjs#1]
Hi, I was having issues with using this code on Wix as I am not 100% sure where the HTML you placed should go? Would you be able to give me a few pointers?

**Comment by Salman2301** [comment]
Hi,
You need to use embed element
and set the URL `https://salman2301.github.io/wix-chartjs/`

1. Click on add element
2. Drag and Drop `Embed element`
3. Click on the setting icon and set the URL to `https://salman2301.github.io/wix-chartjs/`
